/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as recyclingcreditsRwaSol from "./RECYCLINGCREDITS_RWA.sol";
export type { recyclingcreditsRwaSol };
